### ISSUE TITLE
Missing documentation for unsupported combination in RandomSplitter

### ISSUE THREAD

**Issue by aleSuglia** [recommenders/rival#119]
Hello,

using the *RandomSplitter* I have verified that there is a combination actually not supported (why?) which is not documented. I think that can be useful for users to be aware of this behaviour. In fact, in this case the resulting splits are completely empty and isn't displayed any error message.

See this for reference: https://github.com/recommenders/rival/blob/master/rival-split/src/main/java/net/recommenders/rival/split/splitter/RandomSplitter.java#L99

Cheers,
Alessandro

**Comment by abellogin** [comment]
Thank you for noticing.

Indeed, it is a problem since there is no warning displayed.

Thanks again.
Alejandro

**Comment by aleSuglia** [comment]
If you want I have implemented a simple fix in my fork. Here there is the related commit: https://github.com/aleSuglia/rival/commit/e7d347f0cc35ab78d0c9084888145d9f63e8fc52

**Comment by alansaid** [comment]
@aleSuglia please do a pull request.
