### ISSUE TITLE
Add custom behaviour to DataModelUtils.saveModel

### ISSUE THREAD

**Issue by aleSuglia** [recommenders/rival#120]
Hello,

using the *saveModel* method of the *DataModelUtils* it is not possible to specify a field delimiter that is used to write the lines on the file. 

In order to be consistent with the loading procedure (implemented by *SimpleParser*), the method that can be used to save the model should allow users to specify the field delimiter. Do you think that it is an appropriate request?

P.S. 
Why do you insert a "-1" as an additional column? Is it required?

Best,
Alessandro

**Comment by abellogin** [comment]
Good point!
DMU should receive a field delimiter in both methods.

The "-1" is added to have the same field generated with a DataModel or a TemporalDataModel.

Best,
Alejandro

**Comment by aleSuglia** [comment]
I have implemented a fix for this issue in my fork. Here there is the related commit: https://github.com/aleSuglia/rival/commit/e9f996f1aedd252f0bbdc2d7ae4bdc5bb328d9ee

**Comment by alansaid** [comment]
@aleSuglia perfect! Please do a pull request an we'll merge it.
