### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by alansaid** [recommenders/rival#126]
Do we want to raise these [numbers](https://codecov.io/gh/recommenders/rival)?

**Comment by afcarvalho1991** [comment]
Hello @alansaid ,

Do you refer to the coverage metric? http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.464.8494&rep=rep1&type=pdf

Seems that this is still a broad concept, there no clear definition for coverage. 
Do you have your own implementation? If so, what is the formula being used. 

Thanks, 
André

**Comment by alansaid** [comment]
Hi @afcarvalho1991 ,
The numbers I refer to are not related to recommender systems, they are related to how much of the code in RiVal is covered/checked by unit tests. 

Currently we have very few of those (~17%), meaning  that there is a lot of functionality that is implemented but not tested.

/A

**Comment by abellogin** [comment]
Hi @alansaid,

thanks for this tool, it could be very useful as a guide for newcomers so they can implement tests of the missing pieces and understand the framework at the same time.

Right now, it looks like the most covered module is the evaluation one, that is good. However, it would not be too difficult to add tests in the split and core modules.

So, definitively this is a good idea and we should aim at raising those numbers in every release.

Cheers,
Alex
