### ISSUE TITLE
C# interface

### ISSUE THREAD

**Issue by alansaid** [recommenders/rival#47]
C# interface through IKVM or similar
http://www.ikvm.net/

**Comment by abellogin** [comment]
Or jni4net http://jni4net.com/

**Comment by alansaid** [comment]
anyone will do. I'm expecting they're all as (in)efficient at handling large objects etc.

**Comment by abellogin** [comment]
Although I agree with closing this issue, I have just realised that another possibility could be to use [Apache Thrift](http://thrift.apache.org/) to communicate with recommendation libraries written in other languages.
