### ISSUE TITLE
Statistical significance

### ISSUE THREAD

**Issue by alansaid** [recommenders/rival#65]
The statistical ssignificance of the improvements compared to a baseline

**Comment by abellogin** [comment]
I can addrees this using Apache Commons Math:
http://commons.apache.org/proper/commons-math/userguide/stat.html#a1.8_Statistical_tests
http://stackoverflow.com/questions/5564621/using-apache-commons-math-to-determine-confidence-intervals
What do you think, @alansaid?

**Comment by alansaid** [comment]
I think this is a good idea, @abellogin
