### ISSUE TITLE
More split examples

### ISSUE THREAD

**Issue by alansaid** [recommenders/rival#69]
Create several split examples

**Comment by abellogin** [comment]
A general split example is provided in 81a2b29 (related to issue #54).
I can still prepare one dummy example for every splitting strategy, it should be easy once we already have one example working.

**Comment by alansaid** [comment]
@abellogin is this finished now?

**Comment by abellogin** [comment]
I'd say so. The examples are only done for movielens, tho, but they should be clear enough for anyone to replicate them with any other dataset or recommender.

**Comment by alansaid** [comment]
:+1:
