### ISSUE TITLE
Oryx support

### ISSUE THREAD

**Issue by meteotester** [recommenders/rival#78]
It could be useful to support also Oryx recommender system: https://github.com/cloudera/oryx

**Comment by samarthbhargav** [comment]
+1

It would be great if support for Spark's ALS and GraphLab's CF recommender was added.

**Comment by alansaid** [comment]
@samarthbhargav note that the support is implicit given the output you generate in your chosen framework, i.e. if your produce csv/tsv files with your recsys, you can simply load them into RiVal.

As for specific support of frameworks, there's currently only two of us (me and @abellogin) working actively on RiVal so frameworks we are not familiar with (or using) are not highly prioritized. 

We'd be delighted if you'd be interested in contributing with support of frameworks you are using :-)
