### ISSUE TITLE
RMSE using CrossValidatedMahoutKNNRecommenderEvaluator (@0.2-SNAPSHOT)

### ISSUE THREAD

**Issue by afcarvalho1991** [recommenders/rival#85]
After executing the code 2 times I noticed that the RMSE was raising everytime I executed the code.

Yet, if I delete the folder "data" the RMSE returns to:

    NDCG@10: 0.0292752140037415
    RMSE: 1.108653420946922
    P@10: 0.039915164369035125

Second run:

    NDCG@10: 0.0292752140037415
    RMSE: 3.9881173431634322
    P@10: 0.039915164369035125

Third run:

    NDCG@10: 0.0292752140037415
    RMSE: 7.671051679724568
    P@10: 0.039915164369035125

And so on... 

Thank you,
André

**Comment by abellogin** [comment]
I have been able to replicate the error. I will work on it and let you know once it is fixed. Thanks for the info.
